### ISSUE TITLE
User report: Zoom on mobile

### ISSUE THREAD

**Issue by gailramster** [public-convenience-ltd/toiletmap#1266]
I found a link to your map and it looks great on a desktop computer. But when trying to use it in practice, on an android mobile, I found some problems:

unable to zoom out on mobile. On desktop there are (+) and (-) buttons. But on mobile those buttons, if they exist at all, are off screen and the screen isn't responding to pinch zoom. Only the current position icon appears. I can pan the map, but if I'm in a sparse area I have no idea which direction to pan it. It's less important whether you implement pinch zoom or the buttons, but one of the methods is needed.
unable to add the map's url to my mobile's home screen. Though not totally essential, it makes it a lot easier to use if I can organise it to be part of my Travel Icons group along with journey planner etc. And it seems to be fairly easy to do, according to the instructions at https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen#how_do_you_make_an_app_a2hs-ready -- indeed, to the extent that a site I wrote many years ago already had the required features without having to implement them specifically for the purpose

My mobile is a sony XA-2 (H3113) running lineageOS 16, equivalent to android 9, but it works with most web sites. It uses Openboard keyboard.

**Comment by ob6160** [comment]
Most of these issues should have been resolved by our move to nextjs. Making the project a PWA (progressive web app) is something we will think about along with a full blown app for installation on phones. 

Progress towards that will live in our GitHub project board - closing this issue as a result
