### ISSUE TITLE
User report: postcodes

### ISSUE THREAD

**Issue by gailramster** [public-convenience-ltd/toiletmap#1267]
Also a problem with postcodes 

I type in a postcode (such as w1a 1aa) and follow it with the Enter key. The search result appears briefly and then disappears. To get it back I have to add a space to the end of the search. 
on a desktop, that's less of a problem but a bit clumsy. I hit Enter by habit after typing in a search box, because most other programs require it
on a mobile, that can mean the keyboard stays on screen, hiding half of the map.

My mobile is a sony XA-2 (H3113) running lineageOS 16, equivalent to android 9, but it works with most web sites. It uses Openboard keyboard.

**Comment by ob6160** [comment]
This will hopefully have been solved with the release of the NextJS migration — I can't replicate it. Please reopen if it is still an issue
