### ISSUE TITLE
Add a simple CMS for publishing news and articles

### ISSUE THREAD

**Issue by marxian** [public-convenience-ltd/toiletmap#1269]

**Comment by ob6160** [comment]
just came across this on github recommended: https://github.com/samuelkraft/notion-blog-nextjs Notion is really easy to use and would be a great way to write articles for the website potentially

**Comment by ob6160** [comment]
Closing this issue — will record in our new project planning board

**Comment by ob6160** [comment]
https://www.storyblok.com/a/storyblok/
