### ISSUE TITLE
Toilet details not loading

### ISSUE THREAD

**Issue by gailramster** [public-convenience-ltd/toiletmap#1416]
**Describe the bug**
A toilet is showing as a pin on the map, but the website can't load its details. 
Other toilets are loading correctly.

**To Reproduce**
> Search postcode TS13 5JF

**Screenshots**
<img width="1440" alt="Screenshot 2022-10-12 at 11 41 32" src="https://user-images.githubusercontent.com/2690575/195322697-cc494310-4a51-45e4-889a-691ad1a129ea.png">

**Desktop (please complete the following information):**

Monterey
 Safari 15.4

**Comment by ob6160** [comment]
ah great - thanks for reporting, will take a look soon

**Comment by ob6160** [comment]
hm — i'm struggling to replace this, https://www.toiletmap.org.uk/loos/9f1caf8506c691627e59ba6b will dig around in the logs to see if a recent release fixed it somehow

**Comment by gailramster** [comment]
Working fine now! How odd.
