### ISSUE TITLE
Contributor name not showing when 'logged in' 

### ISSUE THREAD

**Issue by gailramster** [public-convenience-ltd/toiletmap#1428]
**Describe the bug**
In the Explorer, I log in (I've tried gail.ramster@network.rca.ac.uk and gbtoiletmap@gmail.com - at least one of these has permissions) and get the password right. But the Explorer reloads still saying 'log in' and not showing the contributor names. 

is it possible to restore this function? 

Screenshot showing Search page *after* login. 

<img width="1331" alt="Screenshot 2022-11-08 at 11 41 56" src="https://user-images.githubusercontent.com/2690575/200556218-498fd3cf-2c39-49ad-a2a2-9ab30ec41a5c.png">

**Comment by ob6160** [comment]
As discussed outside of this issue, I'm closing this as we're directing efforts here towards planning & making a new (and hopefully better) version of the explorer.

Will make a new github issue to track this :)
